/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface ThemeDefinition {
  id: string;
  name: string;
  icon: string;
  description: string;
  fontSans: string;
  fontHeading: string;
  sidebarBg: string;
  sidebarBorder: string;
  sidebarHeaderBg: string;
  sidebarActiveBadge: string;
  sidebarText: string;
  sidebarHover: string;
  mainBg: string;
  headerBg: string;
  headerBorder: string;
  cardBg: string;
  cardBorder: string;
  cardRoundness: string;
  cardShadow: string;
  buttonPrimary: string;
  buttonSecondary: string;
  bannerGradient: string;
  bannerPattern: string;
  badgeAccent: string;
  glowEffect: string;
  tableHeaderBg: string;
  tableRowHover: string;
}

export const builtInThemes: ThemeDefinition[] = [
  {
    id: "modern-education-pro",
    name: "Modern Education Pro",
    icon: "💎",
    description: "Premium SaaS design. White, indigo & deep slate gradients. Similar to Notion, Stripe, and Linear.",
    fontSans: "font-sans",
    fontHeading: "font-sans tracking-tight font-extrabold",
    sidebarBg: "bg-slate-900 dark:bg-slate-950",
    sidebarBorder: "border-slate-800",
    sidebarHeaderBg: "bg-slate-950",
    sidebarActiveBadge: "bg-indigo-600/20 text-indigo-400 border-l-4 border-indigo-500",
    sidebarText: "text-slate-350 text-slate-400",
    sidebarHover: "hover:bg-slate-800 hover:text-white",
    mainBg: "bg-slate-50 dark:bg-slate-950",
    headerBg: "bg-white/95 dark:bg-slate-900/95 backdrop-blur",
    headerBorder: "border-slate-200 dark:border-slate-800",
    cardBg: "bg-white dark:bg-slate-900",
    cardBorder: "border-slate-200 dark:border-slate-800",
    cardRoundness: "rounded-2xl",
    cardShadow: "shadow-sm hover:shadow-md transition-shadow duration-200",
    buttonPrimary: "bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm shadow-indigo-600/10",
    buttonSecondary: "bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 text-slate-700 dark:text-slate-200",
    bannerGradient: "from-indigo-900 via-[#1e1b4b] to-zinc-950",
    bannerPattern: "🎓",
    badgeAccent: "bg-indigo-50 dark:bg-indigo-950/40 text-indigo-700 dark:text-indigo-400 border border-indigo-120",
    glowEffect: "hover:shadow-indigo-500/10 hover_glow",
    tableHeaderBg: "bg-slate-50 dark:bg-slate-950",
    tableRowHover: "hover:bg-slate-50/50 dark:hover:bg-slate-850/30"
  },
  {
    id: "glassmorphism",
    name: "Glassmorphism Premium",
    icon: "✨",
    description: "Futuristic frosted glass design. Transparent blurs, glowing highlights, and vibrant neon underlays.",
    fontSans: "font-sans",
    fontHeading: "font-sans tracking-wide font-black uppercase text-indigo-700 dark:text-indigo-400",
    sidebarBg: "bg-slate-950/70 dark:bg-slate-950/60 backdrop-blur-xl",
    sidebarBorder: "border-white/10 dark:border-white/5",
    sidebarHeaderBg: "bg-[#0b0f19]/85",
    sidebarActiveBadge: "bg-white/10 text-white border-r-4 border-cyan-400 shadow-[0_0_15px_rgba(34,211,238,0.2)]",
    sidebarText: "text-slate-300",
    sidebarHover: "hover:bg-white/5 hover:text-white",
    mainBg: "bg-gradient-to-tr from-slate-950 via-slate-900 to-indigo-950/70",
    headerBg: "bg-white/10 dark:bg-black/20 backdrop-blur-2xl",
    headerBorder: "border-white/10 dark:border-white/5",
    cardBg: "bg-white/60 dark:bg-slate-900/50 backdrop-blur-lg",
    cardBorder: "border-white/20 dark:border-white/10",
    cardRoundness: "rounded-3xl",
    cardShadow: "shadow-[0_8px_32px_0_rgba(31,38,135,0.07)] border-t border-l border-white/20",
    buttonPrimary: "bg-gradient-to-r from-violet-600 to-cyan-500 hover:from-violet-500 hover:to-cyan-400 text-white shadow-lg shadow-violet-500/20 active:scale-95 transition-transform",
    buttonSecondary: "bg-white/20 backdrop-blur-md text-slate-800 dark:text-white border border-white/10 hover:bg-white/30",
    bannerGradient: "from-gradient-r from-slate-900 via-violet-950 to-indigo-950",
    bannerPattern: "🌟",
    badgeAccent: "bg-cyan-500/10 text-cyan-700 dark:text-cyan-400 border border-cyan-500/25",
    glowEffect: "shadow-[0_0_20px_rgba(139,92,246,0.15)]",
    tableHeaderBg: "bg-white/30 dark:bg-slate-950/10 backdrop-blur-sm",
    tableRowHover: "hover:bg-white/35 dark:hover:bg-slate-900/10"
  },
  {
    id: "dark-academy",
    name: "Dark Academy",
    icon: "🎩",
    description: "Luxurious, high-end design using black velvet charcoal surfaces with prestige gold and silver accents.",
    fontSans: "font-sans",
    fontHeading: "font-serif tracking-normal font-bold italic text-amber-500",
    sidebarBg: "bg-[#0b0b0c] text-neutral-300",
    sidebarBorder: "border-amber-805 border-amber-900/20",
    sidebarHeaderBg: "bg-[#050506]",
    sidebarActiveBadge: "bg-gradient-to-r from-amber-951 to-transparent text-amber-400 border-l-2 border-amber-500",
    sidebarText: "text-neutral-400",
    sidebarHover: "hover:bg-neutral-900 hover:text-amber-400",
    mainBg: "bg-[#0f0f11]",
    headerBg: "bg-[#0b0b0c]",
    headerBorder: "border-neutral-900",
    cardBg: "bg-[#141416]",
    cardBorder: "border-neutral-850 border-neutral-900/70",
    cardRoundness: "rounded-xl",
    cardShadow: "shadow-2xl border border-amber-500/10 hover:border-amber-500/20 transition-all",
    buttonPrimary: "bg-gradient-to-r from-amber-600 to-amber-700 hover:from-amber-500 hover:to-amber-600 text-black font-extrabold shadow-md",
    buttonSecondary: "bg-neutral-900 text-neutral-250 hover:bg-neutral-850 text-neutral-300 border border-neutral-800",
    bannerGradient: "from-[#080809] via-amber-950/20 to-[#141416]",
    bannerPattern: "⚜️",
    badgeAccent: "bg-amber-500/10 text-amber-500 dark:text-amber-400 border border-amber-500/20",
    glowEffect: "shadow-[0_0_15px_rgba(245,158,11,0.06)]",
    tableHeaderBg: "bg-[#0a0a0b]",
    tableRowHover: "hover:bg-neutral-900/40"
  },
  {
    id: "neo-minimal",
    name: "Neo-Minimal",
    icon: "📏",
    description: "Monochrome, thin borders, lots of negative space. Focused on absolute efficiency and sleek visual focus.",
    fontSans: "font-sans",
    fontHeading: "font-mono tracking-tight font-semibold text-black dark:text-white",
    sidebarBg: "bg-white dark:bg-black",
    sidebarBorder: "border-slate-200 dark:border-neutral-900",
    sidebarHeaderBg: "bg-neutral-50 dark:bg-neutral-950",
    sidebarActiveBadge: "bg-neutral-950 text-white dark:bg-white dark:text-black font-mono",
    sidebarText: "text-neutral-500 dark:text-neutral-400",
    sidebarHover: "hover:bg-neutral-100 dark:hover:bg-neutral-900 hover:text-black dark:hover:text-white",
    mainBg: "bg-white dark:bg-neutral-950",
    headerBg: "bg-white dark:bg-black",
    headerBorder: "border-neutral-200 dark:border-neutral-900",
    cardBg: "bg-white dark:bg-black",
    cardBorder: "border-neutral-200 dark:border-neutral-900",
    cardRoundness: "rounded-none",
    cardShadow: "shadow-none border border-neutral-200 dark:border-neutral-900",
    buttonPrimary: "bg-black hover:bg-neutral-800 text-white dark:bg-white dark:hover:bg-neutral-200 dark:text-black font-mono uppercase tracking-widest",
    buttonSecondary: "bg-white dark:bg-neutral-900 text-neutral-800 dark:text-neutral-205 py-2 px-4 shadow-none border border-neutral-200 dark:border-neutral-801",
    bannerGradient: "from-neutral-100 via-white to-neutral-100 dark:from-neutral-900 dark:via-black dark:to-neutral-900",
    bannerPattern: "⚪",
    badgeAccent: "bg-neutral-100 dark:bg-neutral-900 text-neutral-800 dark:text-neutral-200 font-mono tracking-tighter border border-neutral-200 dark:border-neutral-800",
    glowEffect: "",
    tableHeaderBg: "bg-neutral-50 dark:bg-neutral-900/20",
    tableRowHover: "hover:bg-neutral-50 dark:hover:bg-neutral-900/30"
  },
  {
    id: "apple-inspired",
    name: "Apple Inspired",
    icon: "🍎",
    description: "Mac & iCloud aesthetics. Ultra smooth rounded corners, light subtle card backgrounds, fluid animations.",
    fontSans: "font-sans",
    fontHeading: "font-sans tracking-tight font-medium text-slate-900 dark:text-slate-100",
    sidebarBg: "bg-slate-50/80 dark:bg-slate-900/80 backdrop-blur-md",
    sidebarBorder: "border-slate-205 dark:border-slate-800",
    sidebarHeaderBg: "bg-slate-100/50 dark:bg-slate-950/20",
    sidebarActiveBadge: "bg-slate-200 dark:bg-slate-800 text-slate-900 dark:text-white rounded-lg shadow-sm font-semibold",
    sidebarText: "text-slate-650 text-slate-500",
    sidebarHover: "hover:bg-slate-200/50 dark:hover:bg-slate-800/50",
    mainBg: "bg-[#f4f4f6] dark:bg-slate-950",
    headerBg: "bg-slate-50/90 dark:bg-slate-900/90 backdrop-blur-md",
    headerBorder: "border-slate-200/50 dark:border-slate-800/50",
    cardBg: "bg-white dark:bg-slate-900",
    cardBorder: "border-slate-100 dark:border-slate-850",
    cardRoundness: "rounded-3xl",
    cardShadow: "shadow-sm hover:shadow-md transition-all duration-300",
    buttonPrimary: "bg-blue-600 hover:bg-blue-700 text-white rounded-xl shadow-sm transition-colors",
    buttonSecondary: "bg-[#ecedf1] dark:bg-slate-850 text-slate-700 dark:text-slate-350 hover:bg-[#e4e5e9]",
    bannerGradient: "from-[#eae9ee] via-[#f3f2f7] to-[#e4e3e8] dark:from-[#111116] dark:via-[#191924] dark:to-[#111116]",
    bannerPattern: "🍏",
    badgeAccent: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border border-blue-500/10",
    glowEffect: "shadow-[0_2px_12px_rgba(59,130,246,0.05)]",
    tableHeaderBg: "bg-slate-100/40 dark:bg-slate-900",
    tableRowHover: "hover:bg-[#fcfcfd] dark:hover:bg-slate-800/40"
  },
  {
    id: "material-3",
    name: "Material 3 Tonal",
    icon: "🎨",
    description: "Google Material Design 3. Dynamic colors, comfortably rounded pill elements, soft tonal container grids.",
    fontSans: "font-sans",
    fontHeading: "font-sans capitalize tracking-normal font-bold text-indigo-900 dark:text-indigo-200",
    sidebarBg: "bg-stone-100 dark:bg-[#1a120b]",
    sidebarBorder: "border-stone-200 dark:border-stone-800",
    sidebarHeaderBg: "bg-stone-250 bg-stone-200 dark:bg-stone-950",
    sidebarActiveBadge: "bg-indigo-150 text-indigo-950 dark:bg-indigo-950 dark:text-indigo-200 rounded-full font-bold",
    sidebarText: "text-stone-600 dark:text-stone-450",
    sidebarHover: "hover:bg-stone-200 dark:hover:bg-stone-800 rounded-full",
    mainBg: "bg-stone-50 dark:bg-[#120a00]",
    headerBg: "bg-stone-100 dark:bg-[#1a120b]",
    headerBorder: "border-stone-200 dark:border-stone-800",
    cardBg: "bg-white dark:bg-[#251b14]",
    cardBorder: "border-stone-200 dark:border-stone-800",
    cardRoundness: "rounded-3xl",
    cardShadow: "shadow-md hover:shadow-lg transition-transform",
    buttonPrimary: "bg-indigo-300 dark:bg-indigo-400 hover:opacity-90 text-slate-900 font-bold rounded-full",
    buttonSecondary: "bg-stone-200 dark:bg-stone-800 text-stone-700 dark:text-stone-300 rounded-full",
    bannerGradient: "from-[#f4e2d8] via-[#e3dedc] to-[#eac8be] dark:from-[#2c1d1a] dark:via-[#1e1312] dark:to-[#2c1d1a]",
    bannerPattern: "🔷",
    badgeAccent: "bg-cyan-100 dark:bg-cyan-950 text-cyan-900 dark:text-cyan-200 rounded-full px-2.5",
    glowEffect: "",
    tableHeaderBg: "bg-[#f4ebe1] dark:bg-[#1e130c]",
    tableRowHover: "hover:bg-[#faf6f0] dark:hover:bg-[#251b14]"
  },
  {
    id: "cyber-future",
    name: "Cyber Future",
    icon: "⚡",
    description: "Futuristic neon layout. Grid lines scanning, neon cyan & radioactive magenta neon glow borders.",
    fontSans: "font-mono",
    fontHeading: "font-mono tracking-widest font-black uppercase text-pink-500",
    sidebarBg: "bg-[#03001e]",
    sidebarBorder: "border-purple-900/40",
    sidebarHeaderBg: "bg-[#0c002b]",
    sidebarActiveBadge: "bg-purple-950/75 text-cyan-400 border-l-4 border-cyan-400 shadow-[0_0_15px_rgba(34,211,238,0.4)]",
    sidebarText: "text-purple-350 text-purple-300",
    sidebarHover: "hover:bg-purple-900/30 hover:text-pink-400",
    mainBg: "bg-[#020011] text-emerald-400",
    headerBg: "bg-[#03001e]",
    headerBorder: "border-purple-900/30",
    cardBg: "bg-[#080221]",
    cardBorder: "border-purple-800/45",
    cardRoundness: "rounded-xl",
    cardShadow: "shadow-[0_0_15px_rgba(236,72,153,0.07)] border-t border-purple-500/20",
    buttonPrimary: "bg-pink-600 hover:bg-pink-500 text-white font-mono uppercase tracking-widest shadow-[0_0_15px_rgba(219,39,119,0.4)]",
    buttonSecondary: "bg-slate-900 hover:bg-slate-800 text-cyan-400 border border-cyan-500/30",
    bannerGradient: "from-[#080221] via-purple-900/25 to-[#0c002b]",
    bannerPattern: "🤖",
    badgeAccent: "bg-pink-500/10 text-pink-400 border border-pink-500/20 font-mono text-[10px]",
    glowEffect: "shadow-[0_0_25px_rgba(34,211,238,0.12)] hover:border-cyan-400 transition-colors",
    tableHeaderBg: "bg-[#020011]",
    tableRowHover: "hover:bg-purple-950/20"
  },
  {
    id: "corporate-enterprise",
    name: "Corporate Enterprise",
    icon: "🏢",
    description: "Highly structured executive theme. Steel gray, navy blue backgrounds, executive summaries and clean grids.",
    fontSans: "font-sans",
    fontHeading: "font-sans tracking-normal font-black text-slate-800 dark:text-white",
    sidebarBg: "bg-slate-850 bg-[#1e293b] text-slate-205",
    sidebarBorder: "border-slate-700",
    sidebarHeaderBg: "bg-[#0f172a]",
    sidebarActiveBadge: "bg-[#0f172a] text-sky-400 border-l-4 border-sky-400",
    sidebarText: "text-slate-350 text-slate-400",
    sidebarHover: "hover:bg-[#334155] hover:text-white",
    mainBg: "bg-slate-100 dark:bg-slate-950",
    headerBg: "bg-white dark:bg-slate-900",
    headerBorder: "border-slate-300 dark:border-slate-800",
    cardBg: "bg-white dark:bg-slate-900",
    cardBorder: "border-slate-300 dark:border-slate-800",
    cardRoundness: "rounded-lg",
    cardShadow: "shadow-none border border-slate-300 dark:border-slate-804",
    buttonPrimary: "bg-slate-800 hover:bg-slate-900 text-white dark:bg-slate-200 dark:text-slate-900 dark:hover:bg-white font-semibold",
    buttonSecondary: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200 border",
    bannerGradient: "from-[#1e293b] via-[#334155] to-[#475569] dark:from-[#0f172a] dark:via-[#1e293b] dark:to-[#334155]",
    bannerPattern: "💼",
    badgeAccent: "bg-slate-100 dark:bg-slate-850 text-slate-800 dark:text-slate-200 border font-semibold",
    glowEffect: "",
    tableHeaderBg: "bg-slate-200/50 dark:bg-slate-950",
    tableRowHover: "hover:bg-slate-50 dark:hover:bg-slate-850/20"
  },
  {
    id: "education-campus",
    name: "Education Campus",
    icon: "🏫",
    description: "Cheerful design. Vibrant sunny amber and active field green, responsive widgets, and campus details.",
    fontSans: "font-sans",
    fontHeading: "font-sans tracking-tight font-extrabold text-amber-705 dark:text-amber-400",
    sidebarBg: "bg-emerald-800 text-white",
    sidebarBorder: "border-emerald-900",
    sidebarHeaderBg: "bg-emerald-950/60",
    sidebarActiveBadge: "bg-amber-400 text-emerald-950 rounded-xl font-black shadow-md",
    sidebarText: "text-emerald-100",
    sidebarHover: "hover:bg-emerald-700 hover:text-white rounded-xl",
    mainBg: "bg-[#fffef5] dark:bg-slate-950",
    headerBg: "bg-amber-100/50 dark:bg-slate-900/90 backdrop-blur-sm",
    headerBorder: "border-amber-200 dark:border-slate-800",
    cardBg: "bg-white dark:bg-slate-900",
    cardBorder: "border-emerald-105 border-amber-200 dark:border-slate-800",
    cardRoundness: "rounded-3xl",
    cardShadow: "shadow-[6px_6px_0px_#10b981] hover:translate-x-[-2px] hover:translate-y-[-2px] transition-transform duration-200",
    buttonPrimary: "bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold rounded-2xl shadow-[4px_4px_0px_#db2777]",
    buttonSecondary: "bg-pink-100 hover:bg-pink-200 text-pink-700 dark:bg-pink-950 dark:text-pink-300 rounded-2xl",
    bannerGradient: "from-emerald-800 via-teal-900 to-amber-951 dark:from-emerald-950 dark:via-slate-900 dark:to-[#0f172a]",
    bannerPattern: "🎨",
    badgeAccent: "bg-amber-100 dark:bg-amber-900 text-amber-800 dark:text-amber-200 border border-amber-300 rounded-full",
    glowEffect: "shadow-[0_4px_14px_rgba(16,185,129,0.15)]",
    tableHeaderBg: "bg-emerald-50 dark:bg-emerald-950/20",
    tableRowHover: "hover:bg-[#fffefd] dark:hover:bg-slate-800/10"
  },
  {
    id: "luxury-gold",
    name: "Luxury Gold Prestige",
    icon: "⚜️",
    description: "Exclusive enterprise design. Deep black lacquer surfaces combined with Champagne Ivory and Gold leaf trim.",
    fontSans: "font-sans",
    fontHeading: "font-serif tracking-widest uppercase font-light text-amber-500",
    sidebarBg: "bg-stone-950 text-amber-500/90",
    sidebarBorder: "border-amber-400/20",
    sidebarHeaderBg: "bg-black",
    sidebarActiveBadge: "bg-amber-451 text-amber-400 border-l-2 border-amber-400/70 shadow-sm font-light uppercase tracking-wider",
    sidebarText: "text-amber-600/75",
    sidebarHover: "hover:bg-[#1a1510] hover:text-amber-400",
    mainBg: "bg-stone-900 dark:bg-black",
    headerBg: "bg-stone-950",
    headerBorder: "border-amber-500/20",
    cardBg: "bg-stone-950 dark:bg-[#0d0d0f]",
    cardBorder: "border-amber-500/25",
    cardRoundness: "rounded-2xl",
    cardShadow: "shadow-2xl border border-amber-500/20 hover:border-amber-400 transition-all duration-300",
    buttonPrimary: "bg-gradient-to-r from-amber-500 to-yellow-600 hover:from-amber-400 hover:to-yellow-500 text-stone-950 font-extrabold uppercase tracking-widest",
    buttonSecondary: "bg-stone-850 hover:bg-stone-800 text-amber-400 border border-amber-500/20",
    bannerGradient: "from-stone-950 via-stone-900 to-black",
    bannerPattern: "🔱",
    badgeAccent: "bg-[#2c1d1a]/50 text-amber-400 border border-amber-400/30 rounded-none font-mono text-[9px]",
    glowEffect: "shadow-[0_0_30px_rgba(245,158,11,0.15)]",
    tableHeaderBg: "bg-stone-900",
    tableRowHover: "hover:bg-stone-850/50"
  },
  {
    id: "bento-grid",
    name: "Bento Grid Startup",
    icon: "🍱",
    description: "Asymmetrical grid container architecture. Pop-artz active headers, vibrant color tags, and WWDC layout.",
    fontSans: "font-sans",
    fontHeading: "font-sans tracking-tighter font-black text-slate-900 dark:text-white",
    sidebarBg: "bg-indigo-950 text-indigo-200",
    sidebarBorder: "border-indigo-900/60",
    sidebarHeaderBg: "bg-indigo-950",
    sidebarActiveBadge: "bg-orange-500 text-white rounded-xl shadow-md font-bold",
    sidebarText: "text-indigo-300",
    sidebarHover: "hover:bg-indigo-900 hover:text-white rounded-xl",
    mainBg: "bg-zinc-50 dark:bg-black",
    headerBg: "bg-white/80 dark:bg-[#121214]/80 backdrop-blur",
    headerBorder: "border-zinc-200 dark:border-zinc-800",
    cardBg: "bg-white dark:bg-[#16161a]",
    cardBorder: "border-zinc-200 dark:border-zinc-800",
    cardRoundness: "rounded-3xl",
    cardShadow: "shadow-[0_10px_25px_rgba(0,0,0,0.03)] hover:scale-[1.01] hover:shadow-lg transition-all duration-300",
    buttonPrimary: "bg-indigo-600 hover:bg-indigo-700 text-white rounded-2xl active:scale-95 shadow-lg shadow-indigo-600/15",
    buttonSecondary: "bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 text-zinc-800 dark:text-zinc-200 rounded-2xl",
    bannerGradient: "from-indigo-600 via-purple-600 to-pink-500",
    bannerPattern: "🧩",
    badgeAccent: "bg-orange-100 dark:bg-orange-950 text-orange-700 dark:text-orange-400 border border-orange-500/20",
    glowEffect: "shadow-md hover:shadow-xl",
    tableHeaderBg: "bg-zinc-100/60 dark:bg-[#1a1a20]",
    tableRowHover: "hover:bg-zinc-100/30 dark:hover:bg-zinc-800/30"
  },
  {
    id: "ai-smart",
    name: "AI Smart Advisor",
    icon: "🧠",
    description: "Cutting-edge artificial intelligence theme. Digital cyan glows, predictive telemetry, pulsing waves.",
    fontSans: "font-mono",
    fontHeading: "font-sans tracking-tight font-black text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-indigo-400",
    sidebarBg: "bg-slate-950/95 border-r border-indigo-950",
    sidebarBorder: "border-indigo-950",
    sidebarHeaderBg: "bg-slate-950/80 backdrop-blur-md",
    sidebarActiveBadge: "bg-indigo-600/10 text-cyan-400 border-l-4 border-cyan-400 shadow-[0_0_20px_rgba(34,211,238,0.25)]",
    sidebarText: "text-slate-400",
    sidebarHover: "hover:bg-indigo-950/40 hover:text-cyan-300",
    mainBg: "bg-[#020512]",
    headerBg: "bg-slate-950/90 border-b border-indigo-950/50 backdrop-blur-xl",
    headerBorder: "border-indigo-950/50",
    cardBg: "bg-slate-950/60 backdrop-blur border border-indigo-950/65",
    cardBorder: "border-indigo-950/65",
    cardRoundness: "rounded-2xl",
    cardShadow: "shadow-[0_8px_30px_rgb(0,0,0,0.12)] border-t border-indigo-500/10",
    buttonPrimary: "bg-gradient-to-r from-cyan-500 to-indigo-600 hover:opacity-90 text-white shadow-lg shadow-cyan-500/20 font-bold",
    buttonSecondary: "bg-slate-900 border border-indigo-950 hover:bg-slate-850 text-cyan-400",
    bannerGradient: "from-indigo-950 via-slate-950 to-indigo-900",
    bannerPattern: "🧠💻",
    badgeAccent: "bg-cyan-500/10 text-cyan-400 border border-cyan-500/30 font-bold font-mono tracking-wide",
    glowEffect: "shadow-[0_0_20px_rgba(6,182,212,0.11)]",
    tableHeaderBg: "bg-indigo-950/30",
    tableRowHover: "hover:bg-indigo-950/20"
  }
];
